package com.manager;

public enum ConfigKey {
	
	SUCCESS_MASSAGE_BEGIN,
	SUCCESS_MASSAGE_END,
	SUCCESS_FOUND,
	SUCCESS_REG,
	SUCCESS_REMOVED_AFTER,
	SUCCESS_REMOVED_BEFORE,
	SUCCCESS_AUTH,

	ERROR_MASSAGE,
	ERROR_NO_DB_BEGIN,
	ERROR_NO_DB_AFTER,
	ERROR_WRONG,
	ERROR_AUTH,

	EMAIL_INCORRECT,
	PASS_INCORECT,
	INVALID_MASSAGE,
	CANT_REMOVED,
	LIST_IS_EMPTY,

	GREEN,
	RED,
	
	ADD_PAGE,
	HOME_PAGE,
	DASHBOARD_PAGE,
	AUTHORIZATION_PAGE,
	REGISTRATION_PAGE

}
